### ISSUE TITLE
Docker auto-build fails

### ISSUE THREAD

**Issue by tstruk** [tpm2-software/tpm2-software-container#48]
Since the docker files have been renamed from *.docker to *.docker.m4 all the automated image builds in https://hub.docker.com/repository/docker/tpm2software/tpm2-tss/builds are failing.
Any reason why were these renamed?

**Comment by tstruk** [comment]
Looks like we do not use https://hub.docker.com/ anymore
At least we should update https://github.com/tpm2-software/tpm2-software-container#auto-builds
not to confuse people.

**Comment by williamcroberts** [comment]
I turned off the webhook on github yesterday, I just turned off the autobuild setting on the repo now (per this bug). I kept the org alive but I should probably just kill it as well; so I just deactivated the org and deleted the old repo.

FYI we switched from dockerhub to github container registry because docker started limiting pulls for unauthenticated accounts. Which means, we would exhaust our limit on PRs in no time for some of the more active projects.
